In [15]:
import pandas as pd
import numpy as np
data = pd.read_csv(r"The Data\diabetes.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [16]:
x = data.drop("Outcome", axis=1)
y = data["Outcome"]

In [17]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest =train_test_split(x,y,test_size=0.2, random_state=2)

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(xTrain,yTrain)

LogisticRegression(max_iter=1000)

In [19]:
yPred = model.predict(xTest)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(yTest, yPred)

0.7662337662337663

In [21]:
yProbability = model.predict_proba(xTest)[:,1]
yProbability

array([0.0495401 , 0.17460501, 0.09362911, 0.25511417, 0.63549093,
       0.11671928, 0.06567348, 0.4219615 , 0.04866024, 0.5756737 ,
       0.3387201 , 0.41300367, 0.69858516, 0.19963831, 0.02001466,
       0.8246679 , 0.86659155, 0.03101584, 0.25512391, 0.89492084,
       0.95243858, 0.83479358, 0.11741532, 0.44669184, 0.08923685,
       0.06881204, 0.65114569, 0.41195103, 0.17863047, 0.28688539,
       0.24550266, 0.4389615 , 0.00942765, 0.24257979, 0.3516465 ,
       0.96164307, 0.34360711, 0.80921991, 0.2938088 , 0.05083898,
       0.18185869, 0.08672558, 0.42229063, 0.18738992, 0.0301169 ,
       0.0394977 , 0.24741718, 0.42777442, 0.10529406, 0.37972891,
       0.99355591, 0.106674  , 0.39098586, 0.76880526, 0.36864156,
       0.4577184 , 0.95035337, 0.41991889, 0.39152262, 0.04376676,
       0.37290008, 0.90126606, 0.88176398, 0.88844085, 0.33085019,
       0.06932373, 0.95264   , 0.20056109, 0.26055752, 0.3545999 ,
       0.1035869 , 0.08168585, 0.45045822, 0.09220882, 0.08649

In [22]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(yTest, yProbability)

In [23]:
thresholds

array([       inf, 0.99355591, 0.95264   , 0.95243858, 0.8246679 ,
       0.76880526, 0.76199926, 0.6838953 , 0.67536162, 0.67420296,
       0.65114569, 0.65081087, 0.63549093, 0.58626078, 0.5756737 ,
       0.56972795, 0.52518814, 0.47020064, 0.46122816, 0.45045822,
       0.4389615 , 0.43865225, 0.42229063, 0.41991889, 0.41300367,
       0.41195103, 0.40480194, 0.37972891, 0.36864156, 0.3101773 ,
       0.30880331, 0.27772696, 0.27203958, 0.25512391, 0.25511417,
       0.24741718, 0.24550266, 0.23662694, 0.22886946, 0.18185869,
       0.17863047, 0.17460501, 0.17327101, 0.14637732, 0.140781  ,
       0.11671928, 0.11494605, 0.11000347, 0.106674  , 0.08923685,
       0.08672558, 0.02001466, 0.01930671, 0.00160774])

In [24]:
fpr

array([0.        , 0.        , 0.        , 0.00917431, 0.00917431,
       0.02752294, 0.02752294, 0.0733945 , 0.0733945 , 0.08256881,
       0.08256881, 0.09174312, 0.09174312, 0.10091743, 0.10091743,
       0.11009174, 0.11009174, 0.12844037, 0.12844037, 0.14678899,
       0.14678899, 0.1559633 , 0.1559633 , 0.17431193, 0.17431193,
       0.18348624, 0.18348624, 0.22018349, 0.22018349, 0.30275229,
       0.30275229, 0.35779817, 0.35779817, 0.39449541, 0.39449541,
       0.40366972, 0.40366972, 0.42201835, 0.42201835, 0.53211009,
       0.53211009, 0.5412844 , 0.5412844 , 0.57798165, 0.57798165,
       0.63302752, 0.63302752, 0.66055046, 0.66055046, 0.74311927,
       0.74311927, 0.98165138, 0.98165138, 1.        ])

In [25]:
tpr

array([0.        , 0.02222222, 0.08888889, 0.08888889, 0.28888889,
       0.28888889, 0.31111111, 0.31111111, 0.33333333, 0.33333333,
       0.37777778, 0.37777778, 0.4       , 0.4       , 0.44444444,
       0.44444444, 0.48888889, 0.48888889, 0.53333333, 0.53333333,
       0.57777778, 0.57777778, 0.62222222, 0.62222222, 0.64444444,
       0.64444444, 0.66666667, 0.66666667, 0.73333333, 0.73333333,
       0.75555556, 0.75555556, 0.77777778, 0.77777778, 0.8       ,
       0.8       , 0.82222222, 0.82222222, 0.84444444, 0.84444444,
       0.86666667, 0.86666667, 0.88888889, 0.88888889, 0.91111111,
       0.91111111, 0.93333333, 0.93333333, 0.95555556, 0.95555556,
       0.97777778, 0.97777778, 1.        , 1.        ])

In [26]:
import plotly.graph_objects as go


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 5
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices], 
    y=tpr[indices], 
    mode='markers+text', 
    name='Threshold points', 
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]], 
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate')
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()

In [27]:
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)

Optimal threshold is: 0.36864155794401016


In [28]:
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(xTrain)
X_test_scaled = scaler.transform(xTest)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(xTrain, yTrain)
lr_scores = lr_model.predict_proba(xTest)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, yTrain)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(yTest, lr_scores)
lr_auc = roc_auc_score(yTest, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(yTest, svm_scores)
svm_auc = roc_auc_score(yTest, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate')
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


# End