In [82]:
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score
import plotly.graph_objects as go 
import plotly.express as px
import numpy as np

In [83]:
x = 6*np.random.rand(200, 1) - 3
x.shape

(200, 1)

In [84]:
y = 0.8*x**2 + 0.9*x + 2 + np.random.rand(200, 1)
y.shape

(200, 1)

In [85]:
px.scatter(x=x.ravel(),y=y.ravel())

In [86]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.2, random_state=2)

In [87]:
xTrain.shape, xTest.shape, yTrain.shape, yTest.shape

((160, 1), (40, 1), (160, 1), (40, 1))

In [88]:
lr = LinearRegression()
lr.fit(xTrain,yTrain)

LinearRegression()

In [89]:
yPred = lr.predict(xTest)
yPred.shape

(40, 1)

In [90]:
lr.intercept_, lr.coef_

(array([5.13553077]), array([[1.03062455]]))

In [91]:
r2_score(yTest, yPred)

0.2525369483794351

In [92]:
px.scatter(x=xTrain.ravel(), y=yTrain.ravel(), trendline="ols", trendline_color_override="red")

In [93]:
# Applying Polynomial Regression 
# For degree = 2
poly =PolynomialFeatures(degree=2, include_bias=True)

In [94]:
xTrainTrans = poly.fit_transform(xTrain)
xTestTrans = poly.transform(np.sort(xTest, axis=0))

In [95]:
print(xTrain[0])
print(xTrainTrans[0])

[2.58670405]
[1.         2.58670405 6.69103786]


In [96]:
lr = LinearRegression()

In [97]:
lr.fit(xTrainTrans,yTrain)

LinearRegression()

In [98]:
yPred = lr.predict(xTestTrans)

In [99]:
r2_score(yTest,yPred)

-1.2168516410819783

In [100]:
lr.intercept_, lr.coef_

(array([2.51092067]), array([[0.        , 0.87400417, 0.79915018]]))

In [101]:
fig = px.scatter(x=xTrain.ravel(), y= yTrain.ravel())
fig.add_traces(go.Scatter(x= xTest.ravel(), y= yTest.ravel(), mode="markers"))
fig.add_traces(go.Scatter(x= np.sort(xTest.ravel()), y=yPred.ravel(), mode="lines"))
fig.show()

### 3D Polynomial Regression

In [102]:
x = 7 * np.random.rand(100, 1) - 2.8
y = 7 * np.random.rand(100, 1) - 2.8
z = x**2 + y**2 + 0.2*x + 0.2*y + 0.1*x*y + 2 + np.random.randn(100, 1)

In [103]:
px.scatter_3d(x=x.ravel(),y=y.ravel(),z=z.ravel())

In [104]:
lr = LinearRegression()
lr.fit(np.array([x,y]).reshape(100,2), z)

LinearRegression()

In [105]:
xInput = np.linspace(x.min(), x.max(), 10)
yInput = np.linspace(y.min(), y.max(), 10)
xGrid, yGrid = np.meshgrid(xInput,yInput)

In [106]:
xGrid

array([[-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989,  3.42622582,  4.19624175],
       [-2.7339016 , -1.96388568, -1.19386975, -0.42385382,  0.34616211,
         1.11617804,  1.88619396,  2.65620989

In [107]:
yGrid

array([[-2.74732144, -2.74732144, -2.74732144, -2.74732144, -2.74732144,
        -2.74732144, -2.74732144, -2.74732144, -2.74732144, -2.74732144],
       [-1.99219545, -1.99219545, -1.99219545, -1.99219545, -1.99219545,
        -1.99219545, -1.99219545, -1.99219545, -1.99219545, -1.99219545],
       [-1.23706945, -1.23706945, -1.23706945, -1.23706945, -1.23706945,
        -1.23706945, -1.23706945, -1.23706945, -1.23706945, -1.23706945],
       [-0.48194346, -0.48194346, -0.48194346, -0.48194346, -0.48194346,
        -0.48194346, -0.48194346, -0.48194346, -0.48194346, -0.48194346],
       [ 0.27318253,  0.27318253,  0.27318253,  0.27318253,  0.27318253,
         0.27318253,  0.27318253,  0.27318253,  0.27318253,  0.27318253],
       [ 1.02830852,  1.02830852,  1.02830852,  1.02830852,  1.02830852,
         1.02830852,  1.02830852,  1.02830852,  1.02830852,  1.02830852],
       [ 1.78343452,  1.78343452,  1.78343452,  1.78343452,  1.78343452,
         1.78343452,  1.78343452,  1.78343452

In [108]:

xGrid.shape, yGrid.shape

((10, 10), (10, 10))

In [109]:
final = np.vstack((xGrid.ravel().reshape(1,100), yGrid.ravel().reshape(1,100))).T
zFinal = lr.predict(final).reshape(10,10)

In [110]:
zFinal.shape

(10, 10)

In [111]:
fig = px.scatter_3d(x= x.ravel(), y= y.ravel(), z=z.ravel())
fig.add_trace(go.Surface(x= xInput.ravel(), y= yInput.ravel(), z=zFinal))
fig.show()

In [112]:
xMulti = np.array([x,y]).reshape(100,2)
xMulti.shape

(100, 2)

In [113]:
poly = PolynomialFeatures(degree=3)
xMultiTran = poly.fit_transform(xMulti)

In [114]:
xMultiTran.shape

(100, 10)

In [115]:
poly.n_features_in_

2

In [116]:
poly.n_output_features_

10

In [117]:
poly.powers_

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 0],
       [1, 1],
       [0, 2],
       [3, 0],
       [2, 1],
       [1, 2],
       [0, 3]], dtype=int64)

In [118]:
lr = LinearRegression()
lr.fit(xMultiTran, z)

LinearRegression()

In [119]:
xTestMulti = poly.transform(final)

In [120]:
zFinal = lr.predict(xMultiTran).reshape(10,10)

In [121]:
fig = px.scatter_3d(x=x.ravel(),y=y.ravel(),z=z.ravel())
fig.add_trace(go.Surface(x= xInput, y= yInput, z= zFinal))

# End