In [1]:
import numpy as np
arr = np.array([[1,1,1,1,1,1,1,1,1,1],[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[1.2, 2.1, 3.1, 4.1, 5.0, 6.0, 7.0, 8.0, 9.1, 10.2]]).T
arr

array([[ 1. ,  1. ,  1.2],
       [ 1. ,  2. ,  2.1],
       [ 1. ,  3. ,  3.1],
       [ 1. ,  4. ,  4.1],
       [ 1. ,  5. ,  5. ],
       [ 1. ,  6. ,  6. ],
       [ 1. ,  7. ,  7. ],
       [ 1. ,  8. ,  8. ],
       [ 1. ,  9. ,  9.1],
       [ 1. , 10. , 10.2]])

In [2]:
np.linalg.cond(np.dot(arr.T,arr))

29104.19736331761

In [3]:
np.linalg.inv(np.dot(arr.T,arr))

array([[  0.67713004,   1.89686099,  -1.97309417],
       [  1.89686099,  18.3309417 , -18.40807175],
       [ -1.97309417, -18.40807175,  18.49775785]])

In [4]:
arr = np.array([[1,1,1,1,1,1,1,1,1,1],[1.1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[1.2, 2.1, 3.1, 4.1, 5.0, 6.0, 7.0, 8.0, 9.1, 10.2]]).T
np.linalg.inv(np.dot(arr.T,arr))

array([[  0.579715  ,   1.55493605,  -1.62140011],
       [  1.55493605,  24.45470752, -24.42659041],
       [ -1.62140011, -24.42659041,  24.41073715]])

In [5]:
arr = np.array([[1,1,1,1,1,1,1,1,1,1],[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[2.4, 0.7, 4.3, 3.5, 1.6, 5.1, 6.9, 7.5, 8.1, 9.8]]).T
np.linalg.inv(np.dot(arr.T,arr))

array([[ 0.46684896, -0.06359872, -0.00341803],
       [-0.06359872,  0.06375331, -0.05752395],
       [-0.00341803, -0.05752395,  0.06408812]])

In [6]:
arr = np.array([[ 0.46684896, -0.06359872, -0.00341803],
       [-0.06359872,  0.06375331, -0.05752395],
       [-0.00341803, -0.05752395,  0.06408812]])
np.linalg.cond(arr)

341.04169922403804

In [7]:
arr = np.array([[1,1,1,1,1,1,1,1,1,1],[1.1, 2, 3, 4, 5, 6, 7, 8, 9, 10],[2.4, 0.7, 4.3, 3.5, 1.6, 5.1, 6.9, 7.5, 8.1, 9.8]]).T
np.linalg.inv(np.dot(arr.T,arr))

array([[ 0.47202303, -0.06705466, -0.00051139],
       [-0.06705466,  0.06552638, -0.05891698],
       [-0.00051139, -0.05891698,  0.06515911]])

In [8]:
import pandas as pd
import seaborn as sns
import plotly.express as px

### 1. Corellation

In [9]:
df = pd.read_csv(r"The Data\Advertising.csv")
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [10]:
df.corr()

Unnamed: 0        TV     Radio  Newspaper     Sales
Unnamed: 0    1.000000  0.017715 -0.110680  -0.154944 -0.051616
TV            0.017715  1.000000  0.054809   0.056648  0.782224
Radio        -0.110680  0.054809  1.000000   0.354104  0.576223
Newspaper    -0.154944  0.056648  0.354104   1.000000  0.228299
Sales        -0.051616  0.782224  0.576223   0.228299  1.000000

In [11]:
px.imshow(df.corr(), text_auto=True, aspect="auto")

### 2. VIF

In [12]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = []
for i in range(df.shape[1]-2):
    vif.append(variance_inflation_factor(df.iloc[:,1:4], i))

In [13]:
pd.DataFrame({"vif":vif}, index=df.columns[1:4]).T

TV     Radio  Newspaper
vif  2.486772  3.285462   3.055245

### 3. Condition Number

In [14]:
a = np.array([[1, 2], [3, 4]])
cn = np.linalg.cond(a)
print("Condition Number : ", cn)

Condition Number :  14.933034373659268


### How To Remove MultiCollinearity?

In [15]:
from sklearn.datasets import make_regression
import statsmodels.api as sm
np.random.seed(42)
x, y = make_regression(n_samples=100, n_features=3, noise=0.5, random_state=42)
# Introduce Multicollinearity between 0 and 1
x[:, 1] = x[:, 0] + 0.5*np.random.normal(size=100)

data = pd.DataFrame(x, columns=["x1", "x2", "x3"])
data["y"] = y
data

x1        x2        x3           y
0  -0.792521 -0.544164 -0.114736   13.480582
1   0.280992  0.211860 -0.622700  -18.902685
2   0.791032  1.114876 -0.909387  110.450979
3   0.625667  1.387182 -0.857158  -78.162124
4  -0.342715 -0.459791 -0.802277  -35.728094
..       ...       ...       ...         ...
95  0.651391 -0.080366 -0.315269   68.841646
96  1.586017  1.734077 -1.237815  183.634164
97  0.010233  0.140761 -0.981509   17.531189
98 -0.234587 -0.232030 -1.415371  -63.202789
99 -0.327662 -0.444956 -0.392108 -125.373405

[100 rows x 4 columns]

In [16]:
data.iloc[:,:-1].corr()

x1        x2        x3
x1  1.000000  0.882948 -0.048636
x2  0.882948  1.000000 -0.054696
x3 -0.048636 -0.054696  1.000000

In [17]:
dataWithConstantAll = sm.add_constant(data[["x1", "x2", "x3"]])
dataWithConstantAll

const        x1        x2        x3
0     1.0 -0.792521 -0.544164 -0.114736
1     1.0  0.280992  0.211860 -0.622700
2     1.0  0.791032  1.114876 -0.909387
3     1.0  0.625667  1.387182 -0.857158
4     1.0 -0.342715 -0.459791 -0.802277
..    ...       ...       ...       ...
95    1.0  0.651391 -0.080366 -0.315269
96    1.0  1.586017  1.734077 -1.237815
97    1.0  0.010233  0.140761 -0.981509
98    1.0 -0.234587 -0.232030 -1.415371
99    1.0 -0.327662 -0.444956 -0.392108

[100 rows x 4 columns]

In [18]:
dataWithConstantReduced = sm.add_constant(data[["x1", "x3"]])
dataWithConstantReduced

const        x1        x3
0     1.0 -0.792521 -0.114736
1     1.0  0.280992 -0.622700
2     1.0  0.791032 -0.909387
3     1.0  0.625667 -0.857158
4     1.0 -0.342715 -0.802277
..    ...       ...       ...
95    1.0  0.651391 -0.315269
96    1.0  1.586017 -1.237815
97    1.0  0.010233 -0.981509
98    1.0 -0.234587 -1.415371
99    1.0 -0.327662 -0.392108

[100 rows x 3 columns]

In [19]:
modelAll = sm.OLS(data["y"], dataWithConstantAll).fit()
print(modelAll.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.122
Date:                Wed, 09 Aug 2023   Prob (F-statistic):              0.344
Time:                        11:06:22   Log-Likelihood:                -581.96
No. Observations:                 100   AIC:                             1172.
Df Residuals:                      96   BIC:                             1182.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.6185      8.572      0.655      0.5

In [20]:
modelAll = sm.OLS(data["y"], dataWithConstantReduced).fit()
print(modelAll.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     1.405
Date:                Wed, 09 Aug 2023   Prob (F-statistic):              0.250
Time:                        11:06:22   Log-Likelihood:                -582.25
No. Observations:                 100   AIC:                             1171.
Df Residuals:                      97   BIC:                             1178.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.8245      8.488      0.568      0.5

In [21]:
data['x1_x2_Combined'] = (data['x1'] + data['x2'])/2
dataWithConstantCombined = sm.add_constant(data[["x1_x2_Combined", "x3"]])
dataWithConstantCombined

const  x1_x2_Combined        x3
0     1.0       -0.668342 -0.114736
1     1.0        0.246426 -0.622700
2     1.0        0.952954 -0.909387
3     1.0        1.006425 -0.857158
4     1.0       -0.401253 -0.802277
..    ...             ...       ...
95    1.0        0.285513 -0.315269
96    1.0        1.660047 -1.237815
97    1.0        0.075497 -0.981509
98    1.0       -0.233309 -1.415371
99    1.0       -0.386309 -0.392108

[100 rows x 3 columns]

In [22]:
modelAll = sm.OLS(data["y"], dataWithConstantCombined).fit()
print(modelAll.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.033
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     1.643
Date:                Wed, 09 Aug 2023   Prob (F-statistic):              0.199
Time:                        11:06:22   Log-Likelihood:                -582.02
No. Observations:                 100   AIC:                             1170.
Df Residuals:                      97   BIC:                             1178.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              5.2059      8.443      0.

### Partial Least Regression

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.cross_decomposition import PLSRegression

# Generate a synthetic dataset with multicollinearity
np.random.seed(42)
X, y = make_regression(n_samples=100, n_features=3, noise=0.5, random_state=42)
X[:, 1] = X[:, 0] + 0.5 * np.random.normal(size=100)  # Introduce multicollinearity between columns 0 and 1

# Convert data to a pandas DataFrame
data = pd.DataFrame(X, columns=['X1', 'X2', 'X3'])
data['y'] = y

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data[['X1', 'X2', 'X3']], data['y'], test_size=0.2, random_state=42)

# Create a PLS model with 2 components
pls_model = PLSRegression(n_components=2)

# Fit the PLS model using the training data
pls_model.fit(X_train, y_train)

# Predict the output using the test data
y_pred = pls_model.predict(X_test)

# Calculate the mean squared error of the predictions
mse = mean_squared_error(y_test, y_pred)
print("Mean squared error of PLS model:", mse)

Mean squared error of PLS model: 7359.987203343638


# End