In [120]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
import numpy as np
import time

In [121]:
x, y = load_diabetes(return_X_y=True)

In [122]:
x.shape

(442, 10)

In [123]:
y.shape

(442,)

In [124]:
xTrain, xTest, yTrain, yTest = train_test_split(
    x, y, test_size=0.2, random_state=2)

In [125]:
xTrain.shape

(353, 10)

In [126]:
xTest.shape

(89, 10)

In [127]:
yTrain.shape

(353,)

In [128]:
yTest.shape

(89,)

In [129]:
reg = LinearRegression()
reg.fit(xTrain,yTrain)

LinearRegression()

In [130]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [131]:
reg.intercept_

151.88331005254167

In [132]:
yPred = reg.predict(xTest)
yPred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [133]:
r2_score(yTest, yPred)

0.4399338661568968

In [134]:
np.insert(xTrain,0,np.ones(xTrain.shape[0]),axis=1).shape

(353, 11)

In [135]:
class GDRegressor:
    def __init__(self, lr=0.01, epochs=100) -> None:
        self.coef = None
        self.intercept = 0
        self.lr = lr
        self.epochs = epochs

    def fit(self, xTrain, yTrain):
        self.coef = np.ones(xTrain.shape[1])
        loss_slope_i =25
        for i in range(self.epochs):
        # while abs(self.intercept - (self.intercept - (self.lr * loss_slope_i))) >= 0.05:
            # Update all the coffiecents and intercept
            yHat = self.intercept + xTrain.dot(self.coef)
            loss_slope_i = -2 * np.mean(yTrain - (yHat))
            self.intercept = self.intercept - (self.lr * loss_slope_i)
            loss_slope_c = (-2 / xTrain.shape[0]) * (yTrain - yHat).dot(xTrain)
            self.coef = self.coef - (self.lr * loss_slope_c)
        print(self.intercept, self.coef, (yTrain - yHat).shape)

    def predict(self, xTest):
        return self.intercept + (xTest.dot(self.coef))

In [136]:
gdr= GDRegressor(epochs=100, lr=0.05)

In [137]:
start = time.time()
gdr.fit(xTrain,yTrain)
print("time Taken : ", time.time() - start)

150.60315663730645 [  8.89800551   2.45567487  21.81098     17.29548148   8.30952332
   6.55581652 -12.17781554  14.80309867  21.77843962  13.5860728 ] (353,)
time Taken :  0.0020809173583984375


In [138]:
gdr.predict(xTest)

array([151.20594684, 154.11408955, 150.41158224, 146.91938145,
       157.675247  , 156.9634973 , 145.75767525, 146.75791506,
       144.71745541, 153.53727723, 152.99923164, 152.28835178,
       153.97182103, 152.0309428 , 157.19060907, 145.85509185,
       152.55754021, 148.3223023 , 150.09822184, 149.97963346,
       147.14495355, 156.3471601 , 153.43465241, 153.67174647,
       148.21164048, 156.81011348, 154.10688617, 149.75479432,
       142.92224814, 159.79759902, 158.2743344 , 148.06505998,
       143.83395441, 147.98049886, 154.79453687, 152.23834376,
       152.63312569, 155.3052381 , 147.3726489 , 157.84718945,
       148.41274852, 148.74612111, 153.81986927, 153.81330407,
       151.82064461, 150.23111483, 152.90119165, 160.75066155,
       148.23721915, 156.24674921, 157.0280393 , 147.23807475,
       148.93746329, 152.55876411, 154.08696054, 148.41800134,
       153.43828212, 145.22914407, 151.23322431, 148.66662008,
       151.82431702, 153.4646797 , 147.62976638, 153.87

In [139]:
r2_score(yTest, gdr.predict(xTest))

0.051394260131596425

# End