In [104]:
import numpy as np
from sklearn.datasets import make_regression

In [105]:
x, y = make_regression(n_samples=4,n_features=1, n_informative=1,
                       n_targets=1, noise=80, random_state=13)

In [106]:
x.shape

(4, 1)

In [107]:

y

array([  7.21786552,  16.04609925, -27.83756166, 144.36688189])

In [108]:
import plotly.express as px
px.scatter(x=x.flatten(),y=y)

In [109]:
# Let's Apply OLS
from sklearn.linear_model import LinearRegression

In [110]:
reg = LinearRegression()

In [111]:
reg.fit(x,y)

LinearRegression()

In [112]:
reg.coef_

array([78.35063668])

In [113]:
reg.intercept_

26.15963284313262

In [114]:
reg.predict(x)

array([-29.65662909,  61.55941724,  22.67278832,  85.21770852])

In [115]:
px.scatter(x=x.flatten(), y=y, trendline="ols", trendline_color_override="red")

In [116]:
# Lets apply Gradient Descent assuming slope is constant m = 78.35
# and let's assume the starting value for intercept b = 0
yPred = ((78.35 * x) + 0).reshape(4)
yPred

array([-55.81580837,  35.39949674,  -3.48681619,  59.05759577])

In [117]:
import plotly.graph_objects as go
trace0 = go.Scatter(x=x.flatten(), y=y, mode= "markers")
trace = go.Scatter(x=x.flatten(), y=reg.predict(x), mode = "lines")
trace1 = go.Scatter(x=x.flatten(), y=yPred, mode = "lines")
data = [trace0, trace, trace1]
layout = go.Layout(title="Year By Year Performance", xaxis={
                   "title": "x"}, yaxis={"title": "Target"})
fig = go.Figure(data, layout)
fig.show()

In [118]:
m = 78.35
b = 0
loss_slope = -2 * np.sum(y - m * x.ravel() - b)
loss_slope

-209.27763408209216

In [119]:
# lets take learning rate 0.1

lr = 0.1
step_size = loss_slope * lr
step_size

-20.927763408209216

In [120]:
# calculate new intercept value
b = b - step_size
b

20.927763408209216

In [121]:
yPred1 = ((78.35 * x)+b).reshape(4)
yPred1

array([-34.88804496,  56.32726015,  17.44094722,  79.98535918])

In [122]:
trace0 = go.Scatter(x=x.flatten(), y=y, mode= "markers")
trace = go.Scatter(x=x.flatten(), y=reg.predict(x))
trace1 = go.Scatter(x=x.flatten(), y=yPred)
trace2 = go.Scatter(x=x.flatten(), y=yPred1)
data = [trace0, trace, trace1, trace2]
layout = go.Layout(title="Year By Year Performance", xaxis={
                   "title": "x"}, yaxis={"title": "Target"})
fig = go.Figure(data, layout)
fig.show()

In [123]:
loss_slope = -2 * np.sum(y - m * x.ravel() - b)
loss_slope

-41.85552681641843

In [124]:
lr = 0.1
step_size = loss_slope * lr
step_size

-4.185552681641844

In [125]:
b = b - step_size
b

25.11331608985106

In [126]:
yPred2 = ((78.35 * x)+b).reshape(4)
yPred2

array([-30.70249228,  60.51281283,  21.6264999 ,  84.17091186])

In [127]:
trace0 = go.Scatter(x=x.flatten(), y=y, mode= "markers")
trace = go.Scatter(x=x.flatten(), y=reg.predict(x))
trace1 = go.Scatter(x=x.flatten(), y=yPred)
trace2 = go.Scatter(x=x.flatten(), y=yPred1)
trace3 = go.Scatter(x=x.flatten(), y=yPred2)
data = [trace0, trace, trace1, trace2, trace3]
layout = go.Layout(title="Year By Year Performance", xaxis={
                   "title": "x"}, yaxis={"title": "Target"})
fig = go.Figure(data, layout)
fig.show()

In [128]:
loss_slope = -2 * np.sum(y - m * x.ravel() - b)
loss_slope

-8.371105363283675

In [129]:
lr = 0.1
step_size = loss_slope * lr
step_size

-0.8371105363283675

In [130]:
b = b - step_size
b

25.95042662617943

In [131]:
yPred3 = ((78.35 * x)+b).reshape(4)
yPred3

array([-29.86538175,  61.34992337,  22.46361044,  85.00802239])

In [132]:
trace0 = go.Scatter(x=x.flatten(), y=y, mode= "markers")
trace = go.Scatter(x=x.flatten(), y=reg.predict(x))
trace1 = go.Scatter(x=x.flatten(), y=yPred)
trace2 = go.Scatter(x=x.flatten(), y=yPred1)
trace3 = go.Scatter(x=x.flatten(), y=yPred2)
trace4 = go.Scatter(x=x.flatten(), y=yPred3)
data = [trace0, trace, trace1, trace2, trace3, trace4]
layout = go.Layout(title="Year By Year Performance", xaxis={
                   "title": "x"}, yaxis={"title": "Target"})
fig = go.Figure(data, layout)
fig.show()

In [133]:
# Do it in Loop
b = -261
m = 78.35
lr = 0.1
epoachs = 0
yPred = 0
loss_slope = 0
trace0 = go.Scatter(x=x.flatten(), y=y, mode= "markers")
trace = go.Scatter(x=x.flatten(), y=reg.predict(x), mode='lines')
data = [trace0, trace]
loss_slope = 25
# for i in range(epoachs):
while (abs((b - (lr * loss_slope)) - b) >= 0.00001):
    loss_slope = -2 * np.sum(y-m * x.ravel() - b)
    b = b - (lr * loss_slope) 
    yPred = (m * x + b).reshape(4)

    data.append(go.Scatter(x=x.flatten(), y=yPred, mode='lines'))
    epoachs +=1
print(epoachs)

layout = go.Layout(title="Year By Year Performance", xaxis={
                   "title": "x"}, yaxis={"title": "Target"})
fig = go.Figure(data, layout)
fig.show()

12


# End