In [1223]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
import numpy as np
import random

In [1224]:
x, y = load_diabetes(return_X_y=True)

In [1225]:
x.shape

(442, 10)

In [1226]:
y.shape

(442,)

In [1227]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.2, random_state=2)

In [1228]:
xTrain.shape, xTest.shape, yTrain.shape, yTest.shape

((353, 10), (89, 10), (353,), (89,))

In [1229]:
reg = LinearRegression()

In [1230]:
reg.fit(xTrain,yTrain)

LinearRegression()

In [1231]:
yPred = reg.predict(xTest)
yPred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [1232]:
r2_score(yTest, yPred)

0.4399338661568968

In [1233]:
reg.intercept_, reg.coef_

(151.88331005254167,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [1234]:
class MBGDRegressor:
    def __init__(self, batchSize, lr=0.01, epochs=100) -> None:
        self.coef = None
        self.intercept = 0
        self.lr = lr
        self.epochs = epochs
        self.batchSize = batchSize

    def fit(self, xTrain, yTrain):
        self.coef = np.ones(xTrain.shape[1])
        for i in range(self.epochs):
            for j in range(int(xTrain.shape[0]/self.batchSize)):
                idx = random.sample(range(0, xTrain.shape[0]), self.batchSize)
                yHat = np.dot(xTrain[idx], self.coef) + self.intercept
                loss_slope_i = -2 * np.mean(yTrain[idx] - yHat)
                self.intercept = self.intercept - (self.lr * loss_slope_i)
                loss_slope_c = -2 * np.dot((yTrain[idx] - yHat), xTrain[idx]) /  self.batchSize
                self.coef = self.coef - (self.lr * loss_slope_c)
        print(self.intercept, self.coef)

    def predict(self, xTest):
        return self.intercept + (xTest.dot(self.coef))

In [1235]:
mbgdr = MBGDRegressor(batchSize=5, lr=0.05, epochs=100)

In [1236]:
mbgdr.fit(xTrain, yTrain)

154.57390377306956 [  35.24518775 -138.85942209  450.48237562  306.36973572  -18.88661814
  -85.79977303 -192.08317051  115.41374471  411.29412323  113.78730862]


In [1237]:
yPred = mbgdr.predict(xTest)

In [1238]:
r2_score(yTest, yPred)

0.4509175609256387

### How To Use Mini-Batch GD Using Sicket-Learn

In [1239]:
from sklearn.linear_model import SGDRegressor

In [1240]:
sgd = SGDRegressor(learning_rate="constant", eta0=0.2)

In [1241]:
batchSize = 35
for i in range(100):
    idx = random.sample(range(xTrain.shape[0]), batchSize)
    sgd.partial_fit(xTrain[idx], yTrain[idx])

In [1242]:
yPred = sgd.predict(xTest)

In [1243]:
sgd.intercept_, sgd.coef_

(array([164.99846469]),
 array([  12.38669536, -103.46778001,  440.86724706,  313.86421055,
         -19.75154456,  -96.18807164, -185.88581391,  100.44843621,
         421.80911685,  113.51788992]))

In [1244]:
r2_score(yTest, yPred)

0.4172269548551254

# End