In [1]:
import plotly.express as px
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"The Data\placement.csv")
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [3]:
fig = px.scatter(df, x="cgpa", y="package", title="Nothing TOO", labels={
                 "cgpa": "CGPA", "package": "Package(in LPA)"}, trendline="ols")
fig.update_traces(marker=dict(size=5), selector=dict(mode='markers'))

In [4]:
x = df.iloc[:, 0:1].values
y = df.iloc[:, -1].values
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
xTrain, xTest, yTrain, yTest = train_test_split(
    x, y, test_size=0.2, random_state=2)

In [7]:
xTrain

array([[7.14],
       [8.93],
       [5.42],
       [5.1 ],
       [7.77],
       [6.76],
       [6.89],
       [6.68],
       [7.91],
       [7.89],
       [8.71],
       [7.95],
       [6.61],
       [6.26],
       [6.53],
       [6.42],
       [5.11],
       [6.09],
       [6.93],
       [7.04],
       [5.94],
       [6.05],
       [5.83],
       [5.95],
       [9.31],
       [5.58],
       [7.88],
       [6.13],
       [7.76],
       [4.85],
       [6.19],
       [8.6 ],
       [6.07],
       [7.18],
       [5.12],
       [7.39],
       [8.25],
       [8.28],
       [7.13],
       [7.35],
       [5.66],
       [5.99],
       [8.01],
       [7.14],
       [6.34],
       [6.89],
       [5.42],
       [6.47],
       [7.69],
       [7.4 ],
       [7.28],
       [5.95],
       [7.38],
       [6.93],
       [8.99],
       [7.36],
       [7.08],
       [5.38],
       [7.56],
       [8.22],
       [5.84],
       [6.78],
       [7.19],
       [7.28],
       [6.79],
       [6.12],
       [6.

In [8]:
yTrain

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [9]:
xTest

array([[8.58],
       [7.15],
       [5.88],
       [6.22],
       [4.57],
       [4.79],
       [5.32],
       [6.86],
       [8.35],
       [6.87],
       [8.94],
       [7.9 ],
       [6.93],
       [5.91],
       [7.32],
       [7.82],
       [5.09],
       [7.42],
       [6.94],
       [7.73],
       [6.19],
       [7.28],
       [6.73],
       [7.2 ],
       [8.21],
       [6.75],
       [7.87],
       [7.6 ],
       [8.63],
       [5.12],
       [8.15],
       [7.36],
       [8.31],
       [6.6 ],
       [6.59],
       [7.47],
       [7.93],
       [6.29],
       [6.37],
       [6.47]])

In [10]:

yTest

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(xTrain, yTrain)

LinearRegression()

In [14]:
lr.predict(np.array(xTest[0, 0]).reshape(1, 1))

array([3.89111601])

In [15]:
lr.predict(xTest)

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

In [16]:
px.scatter(x=xTrain.flatten(), y=yTrain, trendline="ols")

In [17]:
m = lr.coef_
m

array([0.55795197])

In [18]:
b = lr.intercept_
b

-0.8961119222429144

In [19]:
px.box(df["package"])

In [20]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [21]:
def adjusted_R2(xTest, yTest):
    n = yTest.shape[0]
    return 1-((1-r2_score(yTest, lr.predict(xTest)))*(n-1)) / (n-1-xTest.shape[1])

In [22]:
print(f"MAE: {mean_absolute_error(yTest, lr.predict(xTest))}")
print(f"MSE: {mean_squared_error(yTest, lr.predict(xTest))}")
print(f"RMSE: {np.sqrt(mean_squared_error(yTest, lr.predict(xTest)))}")
print(f"R2 Score: {r2_score(yTest, lr.predict(xTest))}")
print(f"Adjusted R2 Score: {adjusted_R2(xTest, yTest)}")

MAE: 0.2884710931878175
MSE: 0.12129235313495527
RMSE: 0.34827051717731616
R2 Score: 0.780730147510384
Adjusted R2 Score: 0.7749598882343415


In [23]:
newDf1 = df.copy()
newDf1["irreleventFeature"] = np.random.random(200)
newDf1 = newDf1[["cgpa", "irreleventFeature", "package"]]
newDf1

cgpa  irreleventFeature  package
0    6.89           0.180290     3.26
1    5.12           0.888842     1.98
2    7.82           0.329195     3.25
3    7.42           0.052814     3.67
4    6.94           0.618503     3.57
..    ...                ...      ...
195  6.93           0.796666     2.46
196  5.89           0.344178     2.57
197  7.21           0.795607     3.24
198  7.63           0.307761     3.96
199  6.22           0.124379     2.33

[200 rows x 3 columns]

In [24]:
px.scatter(x=newDf1["irreleventFeature"], y=newDf1["package"])

In [25]:
x = newDf1.iloc[:, 0:2].values
y = newDf1.iloc[:, -1].values

In [26]:
x

array([[6.89000000e+00, 1.80289688e-01],
       [5.12000000e+00, 8.88841872e-01],
       [7.82000000e+00, 3.29194907e-01],
       [7.42000000e+00, 5.28137951e-02],
       [6.94000000e+00, 6.18502743e-01],
       [7.89000000e+00, 2.75998151e-01],
       [6.73000000e+00, 5.19631634e-01],
       [6.75000000e+00, 1.34512652e-01],
       [6.09000000e+00, 6.06913769e-01],
       [8.31000000e+00, 8.37885224e-02],
       [5.32000000e+00, 8.69985237e-01],
       [6.61000000e+00, 9.04323880e-01],
       [8.94000000e+00, 8.77526965e-01],
       [6.93000000e+00, 1.95905504e-02],
       [7.73000000e+00, 3.75463642e-01],
       [7.25000000e+00, 5.70735410e-01],
       [6.84000000e+00, 2.41958228e-01],
       [5.38000000e+00, 1.84422501e-01],
       [6.94000000e+00, 2.09627246e-01],
       [7.48000000e+00, 7.36636521e-01],
       [7.28000000e+00, 9.16954945e-01],
       [6.85000000e+00, 5.18956706e-01],
       [6.14000000e+00, 4.12112198e-01],
       [6.19000000e+00, 4.38400274e-01],
       [6.530000

In [27]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [28]:
xTrain, xTest, yTrain, yTest = train_test_split(
    x, y, test_size=0.2, random_state=2)

In [29]:
xTrain

array([[7.14000000e+00, 4.00915101e-01],
       [8.93000000e+00, 6.03108692e-01],
       [5.42000000e+00, 3.97300367e-01],
       [5.10000000e+00, 4.35113613e-01],
       [7.77000000e+00, 6.71527611e-02],
       [6.76000000e+00, 1.93572783e-01],
       [6.89000000e+00, 8.60355850e-01],
       [6.68000000e+00, 3.23226316e-01],
       [7.91000000e+00, 1.63500355e-01],
       [7.89000000e+00, 2.75998151e-01],
       [8.71000000e+00, 5.90166334e-01],
       [7.95000000e+00, 6.48738500e-01],
       [6.61000000e+00, 9.04323880e-01],
       [6.26000000e+00, 8.20001370e-01],
       [6.53000000e+00, 3.37934744e-01],
       [6.42000000e+00, 9.16044192e-01],
       [5.11000000e+00, 1.21352666e-01],
       [6.09000000e+00, 6.06913769e-01],
       [6.93000000e+00, 8.01441282e-01],
       [7.04000000e+00, 5.68627896e-01],
       [5.94000000e+00, 7.07542981e-01],
       [6.05000000e+00, 9.17719896e-01],
       [5.83000000e+00, 2.04166227e-01],
       [5.95000000e+00, 1.47044598e-01],
       [9.310000

In [30]:
yTrain

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [31]:
xTest

array([[8.58000000e+00, 3.29744282e-01],
       [7.15000000e+00, 7.96052436e-01],
       [5.88000000e+00, 2.18583899e-01],
       [6.22000000e+00, 1.24379019e-01],
       [4.57000000e+00, 1.05178565e-01],
       [4.79000000e+00, 8.57879214e-01],
       [5.32000000e+00, 8.69985237e-01],
       [6.86000000e+00, 1.49802587e-01],
       [8.35000000e+00, 7.78718956e-01],
       [6.87000000e+00, 5.95088147e-01],
       [8.94000000e+00, 8.77526965e-01],
       [7.90000000e+00, 8.40741174e-01],
       [6.93000000e+00, 1.95905504e-02],
       [5.91000000e+00, 2.66286547e-01],
       [7.32000000e+00, 6.95751114e-01],
       [7.82000000e+00, 3.29194907e-01],
       [5.09000000e+00, 3.67210686e-01],
       [7.42000000e+00, 5.28137951e-02],
       [6.94000000e+00, 6.60902714e-01],
       [7.73000000e+00, 3.75463642e-01],
       [6.19000000e+00, 4.38400274e-01],
       [7.28000000e+00, 7.71430103e-01],
       [6.73000000e+00, 5.19631634e-01],
       [7.20000000e+00, 7.94960570e-01],
       [8.210000

In [32]:
yTest

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [33]:
lr= LinearRegression()

In [34]:
lr.fit(xTrain,yTrain)

LinearRegression()

In [35]:
lr.predict(xTest)

array([3.90272008, 3.07405151, 2.40065351, 2.59662831, 1.67562469,
       1.75110469, 2.04656759, 2.9527321 , 3.74584664, 2.93023171,
       4.06937528, 3.49042101, 3.00007042, 2.41441187, 3.17539481,
       3.477977  , 1.94973254, 3.27184449, 2.96520425, 3.42475564,
       2.56005163, 3.14826409, 2.85674314, 3.10206629, 3.67757744,
       2.84881741, 3.49020311, 3.35585982, 3.91627935, 1.9603547 ,
       3.67835544, 3.17857954, 3.76732762, 2.78170162, 2.80304568,
       3.24528326, 3.50871656, 2.60442654, 2.65463239, 2.74384775])

In [36]:
print(f"MAE: {mean_absolute_error(yTest, lr.predict(xTest))}")
print(f"MSE: {mean_squared_error(yTest, lr.predict(xTest))}")
print(f"RMSE: {np.sqrt(mean_squared_error(yTest, lr.predict(xTest)))}")
print(f"R2 Score: {r2_score(yTest, lr.predict(xTest))}")
print(f"Adjusted R2 Score: {adjusted_R2(xTest, yTest)}")

MAE: 0.2886420030283559
MSE: 0.12098732114011963
RMSE: 0.34783231756137845
R2 Score: 0.7812815781552971
Adjusted R2 Score: 0.7694589607582861


In [37]:
newDf2 = df.copy()
newDf2["iq"] = newDf2["package"] + (np.random.randint(-12, 12, 200)/10)
newDf2 = newDf2[["cgpa", "iq", "package"]]
newDf2

cgpa    iq  package
0    6.89  2.56     3.26
1    5.12  1.08     1.98
2    7.82  2.45     3.25
3    7.42  2.47     3.67
4    6.94  2.87     3.57
..    ...   ...      ...
195  6.93  1.26     2.46
196  5.89  3.07     2.57
197  7.21  2.74     3.24
198  7.63  4.96     3.96
199  6.22  2.73     2.33

[200 rows x 3 columns]

In [38]:
px.scatter(x=newDf2["iq"],y=newDf2["package"])

In [39]:
x = newDf2.iloc[:, 0:2].values
y = newDf2.iloc[:, -1].values

In [40]:
x

array([[6.89, 2.56],
       [5.12, 1.08],
       [7.82, 2.45],
       [7.42, 2.47],
       [6.94, 2.87],
       [7.89, 3.39],
       [6.73, 3.  ],
       [6.75, 2.08],
       [6.09, 3.01],
       [8.31, 4.61],
       [5.32, 0.66],
       [6.61, 1.4 ],
       [8.94, 4.75],
       [6.93, 3.09],
       [7.73, 2.42],
       [7.25, 2.73],
       [6.84, 2.75],
       [5.38, 0.99],
       [6.94, 2.08],
       [7.48, 3.63],
       [7.28, 3.76],
       [6.85, 2.83],
       [6.14, 1.6 ],
       [6.19, 2.48],
       [6.53, 2.71],
       [7.28, 3.55],
       [8.31, 3.42],
       [5.42, 2.36],
       [5.94, 2.84],
       [7.15, 2.89],
       [7.36, 3.96],
       [8.1 , 4.89],
       [6.96, 1.98],
       [6.35, 1.53],
       [7.34, 3.62],
       [6.87, 2.37],
       [5.99, 3.04],
       [5.9 , 2.83],
       [8.62, 4.46],
       [7.43, 3.13],
       [9.38, 3.02],
       [6.89, 2.  ],
       [5.95, 3.64],
       [7.66, 2.76],
       [5.09, 0.76],
       [7.87, 3.48],
       [6.07, 2.66],
       [5.84,

In [41]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [42]:
xTrain, xTest, yTrain, yTest = train_test_split(
    x, y, test_size=0.2, random_state=2)

In [43]:
xTrain

array([[7.14, 4.13],
       [8.93, 3.91],
       [5.42, 1.85],
       [5.1 , 1.4 ],
       [7.77, 3.56],
       [6.76, 3.18],
       [6.89, 2.  ],
       [6.68, 2.39],
       [7.91, 2.55],
       [7.89, 3.39],
       [8.71, 4.48],
       [7.95, 3.04],
       [6.61, 1.4 ],
       [6.26, 3.44],
       [6.53, 2.71],
       [6.42, 3.72],
       [5.11, 2.03],
       [6.09, 3.01],
       [6.93, 2.61],
       [7.04, 3.5 ],
       [5.94, 2.84],
       [6.05, 3.18],
       [5.83, 2.22],
       [5.95, 3.64],
       [9.31, 4.97],
       [5.58, 2.97],
       [7.88, 4.24],
       [6.13, 2.49],
       [7.76, 3.64],
       [4.85, 2.44],
       [6.19, 3.42],
       [8.6 , 3.18],
       [6.07, 2.46],
       [7.18, 3.3 ],
       [5.12, 1.08],
       [7.39, 2.55],
       [8.25, 4.75],
       [8.28, 2.67],
       [7.13, 2.43],
       [7.35, 2.38],
       [5.66, 2.11],
       [5.99, 3.04],
       [8.01, 4.46],
       [7.14, 1.83],
       [6.34, 2.69],
       [6.89, 2.56],
       [5.42, 2.36],
       [6.47,

In [44]:
xTest

array([[8.58, 3.3 ],
       [7.15, 2.89],
       [5.88, 0.98],
       [6.22, 2.73],
       [4.57, 1.54],
       [4.79, 1.28],
       [5.32, 0.66],
       [6.86, 1.99],
       [8.35, 4.31],
       [6.87, 2.37],
       [8.94, 4.75],
       [7.9 , 3.5 ],
       [6.93, 3.09],
       [5.91, 2.2 ],
       [7.32, 3.49],
       [7.82, 2.45],
       [5.09, 0.76],
       [7.42, 2.47],
       [6.94, 3.37],
       [7.73, 2.42],
       [6.19, 2.48],
       [7.28, 3.55],
       [6.73, 3.  ],
       [7.2 , 1.83],
       [8.21, 4.38],
       [6.75, 3.56],
       [7.87, 3.48],
       [7.6 , 3.61],
       [8.63, 4.09],
       [5.12, 2.71],
       [8.15, 3.63],
       [7.36, 3.32],
       [8.31, 4.61],
       [6.6 , 2.24],
       [6.59, 3.11],
       [7.47, 3.84],
       [7.93, 3.64],
       [6.29, 3.43],
       [6.37, 2.21],
       [6.47, 1.71]])

In [45]:
yTrain

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [46]:
yTest

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [47]:
lr= LinearRegression()

In [48]:
lr.fit(xTrain,yTrain)

LinearRegression()

In [49]:
lr.predict(xTest)

array([3.79895649, 3.05994663, 2.14729226, 2.59701501, 1.62543388,
       1.68555633, 1.83145197, 2.77463004, 3.85850368, 2.84233266,
       4.20831937, 3.5130308 , 2.98987521, 2.36366543, 3.23920856,
       3.30138395, 1.74010645, 3.11700091, 3.04099622, 3.25417711,
       2.54148351, 3.23038759, 2.88110207, 2.90764391, 3.80441604,
       2.98334409, 3.49563703, 3.39049605, 3.95341369, 2.07752542,
       3.65189901, 3.22978975, 3.8894786 , 2.69407949, 2.83364707,
       3.36763148, 3.55032252, 2.74593371, 2.58117787, 2.54519462])

In [50]:
print(f"MAE: {mean_absolute_error(yTest, lr.predict(xTest))}")
print(f"MSE: {mean_squared_error(yTest, lr.predict(xTest))}")
print(f"RMSE: {np.sqrt(mean_squared_error(yTest, lr.predict(xTest)))}")
print(f"R2 Score: {r2_score(yTest, lr.predict(xTest))}")
print(f"Adjusted R2 Score: {adjusted_R2(xTest, yTest)}")

MAE: 0.27985142201022317
MSE: 0.11821784891108793
RMSE: 0.3438282258789815
R2 Score: 0.7862881738015881
Adjusted R2 Score: 0.7747361831962686


# End