# What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating NumPy Arrays

In [1]:
import numpy as np

In [102]:
# np.array
a = np.array([1, 2, 2, 4])
print(a)
print(type(a))


[1 2 2 4]
<class 'numpy.ndarray'>


In [103]:
# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
# 3D Array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print(type(c))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [105]:
# dtype
np.array([1, 5, 4, 2, 6, 8], dtype=float)


array([1., 5., 4., 2., 6., 8.])

In [106]:
# np.arange similar to range function in python
np.arange(1, 16, 2)


array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [107]:
# with reshape
ar = np.arange(1, 13)
ar.reshape(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
# np.ones
o = np.ones((3, 3), dtype=int)
o


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [109]:
# np.zeros
z = np.zeros((3, 4), dtype=int)
z


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [110]:
# np.random
r = np.random.random((3, 4))
r


array([[0.4176752 , 0.13214617, 0.57699187, 0.57309094],
       [0.80736444, 0.54091108, 0.73475421, 0.57080996],
       [0.39085207, 0.93857579, 0.3845329 , 0.86604551]])

In [111]:
# np.linspace - linearly spaced
ls = np.linspace(10, 50, 5)
ls


array([10., 20., 30., 40., 50.])

In [112]:
# np.identity
i = np.identity(3, dtype=int)
i


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Array Attributes

In [113]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)
print("1D Array\n", a1)
print("2D Array\n", a2)
print("3d Array\n", a3)


1D Array
 [0 1 2 3 4 5 6 7 8 9]
2D Array
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
3d Array
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [114]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


In [115]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


In [116]:
# size - no. of items in array
print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [117]:
# itemsize - memory size occupied by each element
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)


4
8
4


In [118]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int32


### Changing DataTypes

In [119]:
# astype - used to change datatype
print("dtype of array before changing its dtype", a3.dtype)
a3 = a3.astype(np.int16)
print("dtype of array After changing its dtype", a3.dtype)


dtype of array before changing its dtype int32
dtype of array After changing its dtype int16


### Array Operations

In [120]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
print(a1, "\n")
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [121]:
# Scalar Operation
# Arithmetic
print(a1*2, "\n")
print(a1/2, "\n")
print(a1+2, "\n")
print(a1-2, "\n")
print(a1**2, "\n")


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]] 

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]] 

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 



In [122]:
# Relational operators
print(a2 < 16, "\n")
print(a2 == 25, "\n")
print(a2 > 20, "\n")


[[ True  True  True  True]
 [False False False False]
 [False False False False]] 

[[False False False False]
 [False False False False]
 [False False False False]] 

[[False False False False]
 [False False False False]
 [False  True  True  True]] 



In [123]:
# Vector Operations
print(a1 + a2, "\n")
print(a2 - a1, "\n")
print(a1 * a2, "\n")
print(a1 / a2, "\n")


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]] 

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 



Array Functions

In [124]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
print(a1)


[[46. 58. 25.]
 [48. 49. 32.]
 [13. 68. 49.]]


In [125]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))


68.0
13.0
388.0
217451032780800.0


In [126]:
# row/column wise
# axis 0 means columns
# axis 1 means row
print(np.max(a1, axis=0))
print(np.min(a1, axis=1))
print(np.sum(a1, axis=1))
print(np.prod(a1, axis=0))


[48. 68. 49.]
[25. 32. 13.]
[129. 129. 130.]
[ 28704. 193256.  39200.]


In [127]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print(np.mean(a1, axis=0))
print(np.median(a1, axis=1))
print(np.std(a1, axis=1))
print(np.var(a1, axis=0))


43.111111111111114
48.0
15.989193881733199
255.65432098765436
[35.66666667 58.33333333 35.33333333]
[46. 48. 49.]
[13.6381817   7.78888096 22.80838053]
[257.55555556  60.22222222 101.55555556]


In [128]:
# trigonomoetric functions
print(np.sin(a1))


[[ 0.90178835  0.99287265 -0.13235175]
 [-0.76825466 -0.95375265  0.55142668]
 [ 0.42016704 -0.89792768 -0.95375265]]


In [129]:
# dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)
print(a2, "\n")
print(a3, "\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 



In [130]:
np.dot(a2, a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [131]:
# log and exponents
np.log(a1), np.exp(a1)


(array([[3.8286414 , 4.06044301, 3.21887582],
        [3.87120101, 3.8918203 , 3.4657359 ],
        [2.56494936, 4.21950771, 3.8918203 ]]),
 array([[9.49611942e+19, 1.54553894e+25, 7.20048993e+10],
        [7.01673591e+20, 1.90734657e+21, 7.89629602e+13],
        [4.42413392e+05, 3.40427605e+29, 1.90734657e+21]]))

In [132]:
# round - rounf off nearest integer/floor - rounf off lowest integer/ceil - rounf off largest integer
a = np.random.random((2, 3))*100
a, np.round(a), np.floor(a), np.ceil(a)


(array([[24.11253526, 31.42962404, 33.19617651],
        [96.56974679,  8.38320875,  6.46295821]]),
 array([[24., 31., 33.],
        [97.,  8.,  6.]]),
 array([[24., 31., 33.],
        [96.,  8.,  6.]]),
 array([[25., 32., 34.],
        [97.,  9.,  7.]]))

### Indexing and Slicing

In [133]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)
a1, a2, a3


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [134]:
# indexing Same as python
a1[5]


5

In [135]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a2[2, 3]


11

In [137]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [138]:
a3[1, 1, 1]


7

In [139]:
# Slicing
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
# same as python
a1[2:5]


array([2, 3, 4])

In [141]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
# fetch only first row
a2[0, :]


array([0, 1, 2, 3])

In [143]:
# fetch only 3rd column
a2[:, 2]


array([ 2,  6, 10])

In [144]:
# fetch 5,6,9,10
a2[1:3, 1:3]


array([[ 5,  6],
       [ 9, 10]])

In [145]:
# fetch all corner elements
a2[::2, ::3]


array([[ 0,  3],
       [ 8, 11]])

In [146]:
# fetch 1,3,9,11
a2[::2, 1::2]


array([[ 1,  3],
       [ 9, 11]])

In [147]:
# fetch 4, 7
a2[1, ::3]


array([4, 7])

In [148]:
# fetch 1,2,3,5,6,7
a2[:2, 1:]


array([[1, 2, 3],
       [5, 6, 7]])

In [149]:
# in case of 3d
a3 = np.arange(27).reshape(3, 3, 3)
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [150]:
# fetch middle 2d array
a3[1]


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [151]:
# fetch alternate array
a3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
# 2nd row of 1st 2d array
a3[0, 1]


array([3, 4, 5])

In [153]:
# fetch middle column of middle 2d array
a3[1, :, 1]


array([10, 13, 16])

In [154]:
# fetch 22,23,25,26
a3[2, 1:, 1:]


array([[22, 23],
       [25, 26]])

In [156]:
# fetch 0,2,18,20
a3[::2, 0, ::2]


array([[ 0,  2],
       [18, 20]])

### Iterating

In [158]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [162]:
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [167]:
for i in a2:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [169]:
for i in a3:
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [175]:
for i in np.nditer(a3):
    print(i, end=" ")


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

Reshaping

In [179]:
# Transpose
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
np.transpose(a2), a2.T


(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [188]:
# ravel - convert n dimentional array into 1d array
np.ravel(a3)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [189]:
a4 = np.arange(12).reshape(3, 4)
a4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [190]:
a5 = np.arange(12, 24).reshape(3, 4)
a5


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [196]:
# Horizontal Stacking
np.hstack((a4, a5, a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23]])

In [197]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

In [199]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [205]:
# Horizontal Spliting
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [208]:
# Vertical Spliting
np.vsplit(a4, 1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

### Save and Load NumPy Array

In [5]:
arr = np.linspace(10,40,4, dtype=np.int8)
arr

array([10, 20, 30, 40], dtype=int8)

In [6]:
np.save("MyArray", arr)

In [8]:
# Load array
a = np.load(r"MyArray.npy")
a

array([10, 20, 30, 40], dtype=int8)

# End