### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[53, 59, 52, 12],
       [70, 61, 84,  2],
       [99, 30, 64, 95],
       [76,  7,  6, 52],
       [51, 82, 31, 89],
       [92,  2, 38, 45]])

In [4]:
np.sort(a)[::-1]

array([84, 82, 80, 78, 71, 71, 69, 57, 56, 52, 51, 30, 27, 23,  1])

In [5]:
np.sort(b,axis=0)

array([[51,  2,  6,  2],
       [53,  7, 31, 12],
       [70, 30, 38, 45],
       [76, 59, 52, 52],
       [92, 61, 64, 89],
       [99, 82, 84, 95]])

### np.argsort

In [71]:
print(a)
print(a.argsort()) # Returns Index in sorted Order
a[a.argsort()]

[110 530  82  23  71  69   1  52  51  84  27  71  80  30  78]
[ 6  3 10 13  8  7  5  4 11 14 12  2  9  0  1]


array([  1,  23,  27,  30,  51,  52,  69,  71,  71,  78,  80,  82,  84,
       110, 530])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
# code
np.append(a,200)

array([ 57,  56,  82,  23,  71,  69,   1,  52,  51,  84,  27,  71,  80,
        30,  78, 200])

In [8]:
b

array([[53, 59, 52, 12],
       [70, 61, 84,  2],
       [99, 30, 64, 95],
       [76,  7,  6, 52],
       [51, 82, 31, 89],
       [92,  2, 38, 45]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[5.30000000e+01, 5.90000000e+01, 5.20000000e+01, 1.20000000e+01,
        4.28410402e-01],
       [7.00000000e+01, 6.10000000e+01, 8.40000000e+01, 2.00000000e+00,
        1.40638566e-01],
       [9.90000000e+01, 3.00000000e+01, 6.40000000e+01, 9.50000000e+01,
        5.60019754e-01],
       [7.60000000e+01, 7.00000000e+00, 6.00000000e+00, 5.20000000e+01,
        2.71882024e-01],
       [5.10000000e+01, 8.20000000e+01, 3.10000000e+01, 8.90000000e+01,
        9.47588444e-01],
       [9.20000000e+01, 2.00000000e+00, 3.80000000e+01, 4.50000000e+01,
        8.21139724e-02]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
# code
a.shape

(15,)

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis=1)

array([[57],
       [56],
       [82],
       [23],
       [71],
       [69],
       [ 1],
       [52],
       [51],
       [84],
       [27],
       [71],
       [80],
       [30],
       [78]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  7,  8,  9, 11, 12, 14], dtype=int64),)

In [20]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 23,  0,  0,  1,  0,  0,  0, 27,  0,  0, 30,  0])

In [21]:
np.where(a%2 == 0,0,a)

array([57,  0,  0, 23, 71, 69,  1,  0, 51,  0, 27, 71,  0,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
# code
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [23]:
np.argmax(a)

9

In [24]:
b

array([[53, 59, 52, 12],
       [70, 61, 84,  2],
       [99, 30, 64, 95],
       [76,  7,  6, 52],
       [51, 82, 31, 89],
       [92,  2, 38, 45]])

In [25]:
np.argmax(b,axis=0)

array([2, 4, 1, 2], dtype=int64)

In [26]:
np.argmax(b,axis=1)

array([1, 2, 0, 0, 3, 0], dtype=int64)

In [27]:
# np.argmin
np.argmin(a)

6

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [29]:
np.cumsum(a)

array([ 57, 113, 195, 218, 289, 358, 359, 411, 462, 546, 573, 644, 724,
       754, 832])

In [30]:
b

array([[53, 59, 52, 12],
       [70, 61, 84,  2],
       [99, 30, 64, 95],
       [76,  7,  6, 52],
       [51, 82, 31, 89],
       [92,  2, 38, 45]])

In [31]:
np.cumsum(b,axis=1)

array([[ 53, 112, 164, 176],
       [ 70, 131, 215, 217],
       [ 99, 129, 193, 288],
       [ 76,  83,  89, 141],
       [ 51, 133, 164, 253],
       [ 92,  94, 132, 177]])

In [32]:
np.cumsum(b)

array([  53,  112,  164,  176,  246,  307,  391,  393,  492,  522,  586,
        681,  757,  764,  770,  822,  873,  955,  986, 1075, 1167, 1169,
       1207, 1252])

In [33]:
# np.cumprod
np.cumprod(a)

array([         57,        3192,      261744,     6020112,   427427952,
        -572242384,  -572242384,   308167104, -1463346880,  1632913664,
        1138995968,  -735664896,  1276350464,  -364191744,  1657815040])

In [34]:
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [36]:
np.percentile(a,50)

57.0

In [37]:
np.median(a)

57.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [38]:
# code
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [39]:
np.histogram(a,bins=[0,50,100])

(array([ 4, 11], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [40]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [41]:
# code
a


array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [42]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [43]:
# code
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [44]:
np.flip(a)

array([78, 30, 80, 71, 27, 84, 51, 52,  1, 69, 71, 23, 82, 56, 57])

In [45]:
b

array([[53, 59, 52, 12],
       [70, 61, 84,  2],
       [99, 30, 64, 95],
       [76,  7,  6, 52],
       [51, 82, 31, 89],
       [92,  2, 38, 45]])

In [46]:
np.flip(b,axis=1)

array([[12, 52, 59, 53],
       [ 2, 84, 61, 70],
       [95, 64, 30, 99],
       [52,  6,  7, 76],
       [89, 31, 82, 51],
       [45, 38,  2, 92]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [47]:
# code
a

array([57, 56, 82, 23, 71, 69,  1, 52, 51, 84, 27, 71, 80, 30, 78])

In [48]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [49]:
# code
a

array([110, 530,  82,  23,  71,  69,   1,  52,  51,  84,  27,  71,  80,
        30,  78])

In [50]:
np.delete(a,[0,2,4])

array([530,  23,  69,   1,  52,  51,  84,  27,  71,  80,  30,  78])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [51]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.intersect1d(m,n)

array([3, 4, 5])

In [53]:
np.setdiff1d(n,m)

array([6, 7])

In [54]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [55]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [56]:
# code
a

array([110, 530,  82,  23,  71,  69,   1,  52,  51,  84,  27,  71,  80,
        30,  78])

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 71, 69, 25, 52, 51, 75, 27, 71, 75, 30, 75])

In [58]:
# 17. np.swapaxes

In [59]:
# 18. np.uniform

In [60]:
# 19. np.count_nonzero

In [61]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [62]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [63]:

# 25. np.allclose and equals

# End